[package]
name = "bip322_py"
version = "0.1.0"
edition = "2021"

[lib]
name = "bip322"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module", "abi3-py38"] }
bip322 = "0.0.10"
